version: '2'
services:
    phonebookapp-app:
        image: phonebookapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://phonebookapp-mssql:1433;database=PhoneBookApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    phonebookapp-mssql:
        extends:
            file: mssql.yml
            service: phonebookapp-mssql
